services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  kafka:
    image: 'bitnami/kafka:3.8.0'
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  api-gateway:
    image: backend-chat-app/api-gateway
    build:
      context: ./api-gateway
    container_name: backend-chat-app-api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - identify-service

  identify-service:
    image: backend-chat-app/identify-service
    build:
      context: ./identify-service
    container_name: backend-chat-app-identify-service
    ports:
      - "8080:8080"
volumes:
  db-data: