server:
  port: 8000
app:
  api-prefix: /api/v1

#logging:
#  level:
#    # Bật log DEBUG cho toàn bộ Spring Cloud Gateway
#    org.springframework.cloud.gateway: DEBUG
#    # Bật log DEBUG cho các predicate và filter
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
#    # Bật log DEBUG cho các yêu cầu HTTP đi ra từ Gateway
#    reactor.netty.http.client: DEBUG

spring:
  data:
    redis:
      host: redis
      port: 6379
  application:
    name: api-gateway
  cloud:
    gateway:
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true           # BẬT X-Forwarded-*
        prefix-enabled: true    # QUAN TRỌNG: gửi X-Forwarded-Prefix=/api/v1
        host-enabled: true
        port-enabled: true
        proto-enabled: true
      routes:
        - id: identify-service
          uri: http://identify-service:8080
          predicates:
            - Path=${app.api-prefix}/identify/**
          filters:
            - StripPrefix=2
        - id: oauth2-initiate
          uri: http://identify-service:8080
          predicates:
            - Path=${app.api-prefix}/identify/login/oauth2/**
          filters:
            - StripPrefix=2
        - id: oauth2-success
          uri: http://identify-service:8080
          predicates:
            - Path=${app.api-prefix}/identify/auth/oauth2/**
          filters:
            - StripPrefix=2
        - id: oauth2-authorization
          uri: http://identify-service:8080
          predicates:
            - Path=${app.api-prefix}/oauth2/**
          filters:
            - StripPrefix=2
        - id: chat-service
          uri: http://chat-service:8081
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2
        - id: chat-ws
          uri: ws://chat-service:8081
          predicates:
            - Path=${app.api-prefix}/chat/ws/**
          filters:
            - StripPrefix=2
      default-filters:
        - SaveSession
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG